import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
// import { signIn, signOut, useSession } from "next-auth/react";
import { LightMode as LightModeIcon } from '@mui/icons-material'

import { api } from "~/utils/api";
import Badges, { type TBadge } from "~/components/introduction/Badge";
import { useMemo } from "react";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const badges = useMemo<TBadge[]>(() => {
    const randomText = () => (Math.random() + 1).toString(36).substring(8);
    return [{
      alt: 'Typescript',
      id: randomText(),
      image: 'https://img.shields.io/badge/typescript-%23007ACC.svg?style=for-the-badge&logo=typescript&logoColor=white'
    }, {
      alt: 'JavaScript',
      id: randomText(),
      image: 'https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E'
    }]
  }, [])

  return (
    <>
      <Head>
        <title>PetchDev</title>
        <meta name="description" content="Generated by create-t3-app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* <Box sx={{width: '100vw', height: '100vh', background: 'black'}}/> */}
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#000000] to-[#15162c]">
        <div className="fixed top-4 right-4">
          <button className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20">
            {/* <DarkModIcon color="primary"/> */}
            <LightModeIcon className="text-white/80"/>
          </button>
        </div>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">Petch</span>Dev
          </h1>
          <div className="grid grid-cols-1 gap-4 md:gap-8">
            <Link
              className="flex max-w-md flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">My Bio</h3>
              <div className="text-lg">
              Hi, My name is Petch 👋
              </div>
              <ul className="text-sm">
                <li>
                🔭 I’m currently working on King Power Click
                </li>
                <li>
                🌱 I’m currently learning flutter, docker, trpc and advanced typescript
                </li>
              </ul>
            </Link>
          </div>
          <div className="inline-flex text-center gap-2">
            <Badges
              badges={badges}
            />
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            {/* <AuthShowcase /> */}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

/* const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}; */
